# Generated by Django 6.0.4 on 2026-04-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("asset_type", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=255)),
                ("installation_date", models.DateField()),
                (
                    "condition_rating",
                    models.DecimalField(decimal_places=1, max_digits=3),
                ),
                ("remaining_useful_life", models.IntegerField()),
                ("status", models.CharField(max_length=50)),
            ],
        ),
    ]
