# Generated by Django 6.0.6 on 2026-07-11 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_scope_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_name', models.CharField(max_length=255)),
                ('work_done', models.TextField()),
                ('recommendation', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='projects.project')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
