# Generated by Django 6.0.4 on 2026-04-27 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Risk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "probability_of_failure",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "consequence_of_failure",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="assets.asset"
                    ),
                ),
            ],
        ),
    ]
