# Generated by Django 6.0.4 on 2026-04-27 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repair_cost", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "replacement_cost",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "maintenance_cost",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("discount_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="assets.asset"
                    ),
                ),
            ],
        ),
    ]
