# Generated by Django 6.0 on 2026-06-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0002_scenario_related_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, help_text='Annual discount rate as a percentage (e.g. 5.0 for 5%).', max_digits=5),
        ),
    ]
